# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-12 10:48
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
